repos:
  # pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: "isort"
        types_or: ["cython", "pyi", "python"]
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: "python -m pytest test"
        types: ["python"]
        pass_filenames: false
  # post-commit
  - repo: local
    hooks:
      - id: update-version
        name: update version
        language: system
        entry: python -m setuptools_scm --force-write-version-files
        stages: ["post-commit"]
        always_run: true # when the stage is post-commit, it must be true.
        pass_filenames: false
