default_install_hook_types: ["pre-commit", "post-commit", "pre-push"]
default_stages: ["pre-commit", "pre-push", "manual"]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: "isort"
        types_or: ["cython", "pyi", "python"]
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        language: system
        entry: pylint
        types: ["python"]
        args: ["--rcfile", ".pylintrc.toml", "-rn", "-sn"]
  ################
  # post-commit
  ################
  - repo: local
    hooks:
      - id: update-version
        name: update version
        language: system
        entry: python -m setuptools_scm --force-write-version-files
        stages: ["post-commit", "manual"]
        always_run: true # when the stage is post-commit, it must be true.
        pass_filenames: false
  ################
  # pre-push
  ################
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: "python -m pytest test"
        stages: ["pre-push", "manual"]
        types: ["python"]
        pass_filenames: false
  - repo: local
    hooks:
      - id: update-py-packages-info
        name: update python packages info to THIRDPARTY/PY_PACKAGES.md
        language: system
        entry: ./.script_for_dev/update_py_packages_info.sh
        stages: ["pre-push", "manual"]
        always_run: true
        pass_filenames: false
